package com.oldman.manage.common.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemRole<M extends BaseSystemRole<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 角色名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 角色名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 角色状态:0=停用,1=启用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 角色状态:0=停用,1=启用
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
