package com.oldman.manage.common.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemRoleRouter<M extends BaseSystemRoleRouter<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 权限id
	 */
	public void setRouterId(java.lang.Integer routerId) {
		set("router_id", routerId);
	}

    /**
     * 权限id
     */
	public java.lang.Integer getRouterId() {
		return getInt("router_id");
	}

	/**
	 * 角色id
	 */
	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}

    /**
     * 角色id
     */
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}

}
