package com.oldman.manage.common.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemDictList<M extends BaseSystemDictList<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 数据名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 数据名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 字典ID
	 */
	public void setDictId(java.lang.Integer dictId) {
		set("dict_id", dictId);
	}

    /**
     * 字典ID
     */
	public java.lang.Integer getDictId() {
		return getInt("dict_id");
	}

	/**
	 * 数据值
	 */
	public void setVal(java.lang.String val) {
		set("val", val);
	}

    /**
     * 数据值
     */
	public java.lang.String getVal() {
		return getStr("val");
	}

	/**
	 * 状态:0=停用,1=启用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 状态:0=停用,1=启用
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 排序
	 */
	public void setRank(java.lang.Integer rank) {
		set("rank", rank);
	}

    /**
     * 排序
     */
	public java.lang.Integer getRank() {
		return getInt("rank");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
