package com.oldman.manage.common.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemDict<M extends BaseSystemDict<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 字典名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 字典名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 字典编号
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}

    /**
     * 字典编号
     */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

    /**
     * 备注
     */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
