package com.oldman.manage.common.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemConfig<M extends BaseSystemConfig<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 键
	 */
	public void setKey(java.lang.String key) {
		set("key", key);
	}

    /**
     * 键
     */
	public java.lang.String getKey() {
		return getStr("key");
	}

	/**
	 * 配置名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 配置名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 配置选项
	 */
	public void setOptions(java.lang.String options) {
		set("options", options);
	}

    /**
     * 配置选项
     */
	public java.lang.String getOptions() {
		return getStr("options");
	}

	/**
	 * 公开:0否,1是
	 */
	public void setIsPublic(java.lang.Integer isPublic) {
		set("is_public", isPublic);
	}

    /**
     * 公开:0否,1是
     */
	public java.lang.Integer getIsPublic() {
		return getInt("is_public");
	}

}
