package com.oldman.manage.common.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemRouter<M extends BaseSystemRouter<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 权限路径
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}

    /**
     * 权限路径
     */
	public java.lang.String getPath() {
		return getStr("path");
	}

	/**
	 * 上级权限
	 */
	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}

    /**
     * 上级权限
     */
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 权限名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 权限名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 状态:0=停用,1=启用
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 状态:0=停用,1=启用
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 图标
	 */
	public void setFace(java.lang.String face) {
		set("face", face);
	}

    /**
     * 图标
     */
	public java.lang.String getFace() {
		return getStr("face");
	}

	/**
	 * 类型:0=菜单,1=路由权限/按钮
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}

    /**
     * 类型:0=菜单,1=路由权限/按钮
     */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 排序
	 */
	public void setRank(java.lang.Integer rank) {
		set("rank", rank);
	}

    /**
     * 排序
     */
	public java.lang.Integer getRank() {
		return getInt("rank");
	}

}
