package com.oldman.manage.common.model;

import io.jboot.db.annotation.Table;
import com.oldman.manage.common.modelbase.BaseSystemDict;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_dict", primaryKey = "id")
public class SystemDict extends BaseSystemDict<SystemDict> {
	
}
