package com.oldman.manage.common.model;

import io.jboot.db.annotation.Table;
import com.oldman.manage.common.modelbase.BaseSystemConfig;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_config", primaryKey = "id")
public class SystemConfig extends BaseSystemConfig<SystemConfig> {
	
}
