package com.oldman.manage.common.model;

import io.jboot.db.annotation.Table;
import com.oldman.manage.common.modelbase.BaseSystemRouter;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_router", primaryKey = "id")
public class SystemRouter extends BaseSystemRouter<SystemRouter> {
	
}
