package com.oldman.manage.common.model;

import io.jboot.db.annotation.Table;
import com.oldman.manage.common.modelbase.BaseSystemUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_user", primaryKey = "id")
public class SystemUser extends BaseSystemUser<SystemUser> {
	
}
