package com.oldman.manage.common.model;

import io.jboot.db.annotation.Table;
import com.oldman.manage.common.modelbase.BaseSystemUserRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_user_role", primaryKey = "id")
public class SystemUserRole extends BaseSystemUserRole<SystemUserRole> {
	
}
