package com.oldman.manage.common.model;

import io.jboot.db.annotation.Table;
import com.oldman.manage.common.modelbase.BaseSystemRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_role", primaryKey = "id")
public class SystemRole extends BaseSystemRole<SystemRole> {
	
}
