package com.oldman.manage.common.model;

import io.jboot.db.annotation.Table;
import com.oldman.manage.common.modelbase.BaseSystemRoleRouter;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_role_router", primaryKey = "id")
public class SystemRoleRouter extends BaseSystemRoleRouter<SystemRoleRouter> {
	
}
