package com.oldman.manage.common.model;

import io.jboot.db.annotation.Table;
import com.oldman.manage.common.modelbase.BaseSystemDictList;

/**
 * Generated by Jboot.
 */
@Table(tableName = "system_dict_list", primaryKey = "id")
public class SystemDictList extends BaseSystemDictList<SystemDictList> {
	
}
